-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 10-07-2025 a las 00:39:19
-- Versión del servidor: 10.4.27-MariaDB
-- Versión de PHP: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `deeprol`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `razas`
--

CREATE TABLE `razas` (
  `id` int(2) NOT NULL,
  `Nombre` varchar(50) NOT NULL,
  `descr` varchar(3000) NOT NULL,
  `rasgos_raza` text NOT NULL,
  `image_path` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Volcado de datos para la tabla `razas`
--

INSERT INTO `razas` (`id`, `Nombre`, `descr`, `rasgos_raza`, `image_path`) VALUES
(1, 'Dracónido', 'Tu herencia dracónida se manifiesta en una serie de rasgos que compartes con otros dracónidos. Los dracónidos tienden hacia los extremos en la guerra cósmica entre el bien y el mal. La mayoría son buenos, pero los que se ponen de lado del mal pueden ser terriblemente malignos.', ' <h1>Rasgos raciales Dracónido</h1>   <p>Tu personaje Dracónido tiene unos cuantos rasgos en común con el resto de miembros de su raza:</p>    <h2>Velocidad</h2>   <p>30 pies</p>    <h2>Linaje dracónico</h2>   <p>Tienes un antepasado dragón. Elige un tipo de dragón de la siguiente lista. Tu arma de aliento y tu resistencia al daño dependen del dragón elegido:</p>   <ul>     <li>Azul – Relámpago – Línea de 5 a 30 pies (salvación de Destreza)</li>     <li>Blanco – Frío – Cono de 15 pies (salvación de Constitución)</li>     <li>De bronce – Relámpago – Línea de 5 a 30 pies (salvación de Destreza)</li>     <li>De cobre – Ácido – Línea de 5 a 30 pies (salvación de Destreza)</li>     <li>De oro – Fuego – Cono de 15 pies (salvación de Destreza)</li>     <li>De oropel – Fuego – Línea de 5 a 30 pies (salvación de Destreza)</li>     <li>De plata – Frío – Cono de 15 pies (salvación de Constitución)</li>     <li>Negro – Ácido – Línea de 5 a 30 pies (salvación de Destreza)</li>     <li>Rojo – Fuego – Cono de 15 pies (salvación de Destreza)</li>     <li>Verde – Veneno – Cono de 15 pies (salvación de Constitución)</li>   </ul>    <h2>Ataque de aliento</h2>   <p>Puedes usar tu acción para exhalar energía destructiva. Tu antepasado dragón determina el tamaño, forma y tipo de daño del aliento.</p>   <p>Las criaturas en el área del aliento deben hacer una tirada de salvación (según el tipo de dragón). La CD es igual a <strong>8 + tu modificador de Constitución + tu bonificador por competencia</strong>.</p>   <p>Daño:</p>   <ul>     <li>2d6 (nivel 1)</li>     <li>3d6 (nivel 6)</li>     <li>4d6 (nivel 11)</li>     <li>5d6 (nivel 16)</li>   </ul>   <p>Una criatura que falle recibe daño completo. Si tiene éxito, recibe la mitad.</p>   <p>Tras usar tu arma de aliento, debes completar un descanso corto o largo para volver a utilizarla.</p>    <h2>Resistencia al daño</h2>   <p>Tienes resistencia al tipo de daño asociado con tu antepasado dragón.</p>    <h2>Idiomas</h2>   <p>Puedes hablar, leer y escribir <strong>común</strong> y <strong>dracónico</strong>. Se cree que el dracónico es uno de los idiomas más antiguos, a menudo usado en el estudio de la magia. Suena áspero y contiene muchas consonantes duras y sibilantes.</p>    <h2>Modificadores</h2>   <ul>     <li>+2 Fuerza</li>     <li>+1 Carisma</li>   </ul>', ''),
(2, 'Elfo', 'Los elfos circulan libremente por las tierras de los humanos, donde siempre son bienvenidos pero nunca se encuentran como en casa. Son gentes conocidas por su poesía, baile, canto, saber y artes mágicas, y gustan de las cosas cuya belleza sea natural y sencilla.', '<h1>Rasgos raciales Elfo</h1>   <p>Tu personaje Elfo tiene unos cuantos rasgos en común con el resto de miembros de su raza:</p>    <h2>Velocidad</h2>   <p>30 pies</p>    <h2>Visión en la oscuridad</h2>   <p>Estás acostumbrado a la luz crepuscular de los bosques y al cielo nocturno. Puedes ver en la penumbra a una distancia de 60 pies como si fuera luz brillante y, en la oscuridad, como si fuera penumbra. En la oscuridad no puedes distinguir colores, solo tonos de gris.</p>    <h2>Linaje feérico</h2>   <p>Tienes ventaja en las tiradas de salvación para no quedar hechizado y no puedes quedarte dormido por ningún efecto mágico.</p>    <h2>Trance</h2>   <p>Los elfos no necesitan dormir. En lugar de ello, meditan profundamente y permanecen semiinconscientes durante cuatro horas al día (conocido como «trance»). Descansar de este modo te otorga los mismos beneficios que dormir ocho horas a un humano.</p>    <h2>Idiomas</h2>   <p>Puedes hablar, leer y escribir <strong>común</strong> y <strong>élfico</strong>. El élfico es un idioma fluido, con entonaciones sutiles y una gramática intrincada. La literatura élfica es rica y variada, y sus poemas y canciones son famosos entre el resto de razas. Muchos bardos aprenden este idioma para incluir poemas élficos a sus repertorios.</p>    <h2>Modificadores</h2>   <ul style=\"list-style-type: none; padding-left: 0;\">     <li>+2 Destreza</li>     <li>Competencia: Percepción</li>   </ul>', ''),
(3, 'Enano', 'Los enanos son conocidos por su habilidad en el arte de la guerra, su gran resistencia a los castigos, su conocimiento de los secretos de la tierra, su dedicación al trabajo y su capacidad para beber cerveza. Los enanos son gente poco dada a las risas o las bromas, y suelen mostrarse recelosos con los desconocidos; sin embargo, se comportan de forma generosa con los que se ganan su confianza.', '  <h1>Rasgos raciales Enano</h1>   <p>Tu personaje Enano tiene unos cuantos rasgos en común con el resto de miembros de su raza:</p>    <h2>Velocidad</h2>   <p>25 pies</p>    <h2>Visión en la oscuridad</h2>   <p>Tienes una visión superior en la oscuridad y en la penumbra. Puedes ver en la penumbra a una distancia de 60 pies como si fuera luz brillante, y en la oscuridad como si fuera penumbra. En la oscuridad no puedes distinguir colores, solo tonos de gris.</p>    <h2>Fortaleza enana</h2>   <p>Tienes ventaja en las tiradas de salvación contra venenos y eres resistente al daño por veneno.</p>    <h2>Afinidad con la piedra</h2>   <p>Cuando realices una prueba de Inteligencia (Historia) relacionada con el origen de una obra de mampostería, se considera que tienes competencia con la habilidad de Historia y añades a la prueba tu bonificador por competencia multiplicado por 2 en lugar del bonificador habitual.</p>    <h2>Idiomas</h2>   <p>Puedes hablar, leer y escribir <strong>común</strong> y <strong>enano</strong>. El idioma enano está lleno de consonantes duras y sonidos guturales, características que se aplican también a cualquier otra lengua que hable un enano.</p>    <h2>Velocidad enana</h2>   <p>Tu velocidad no se reduce por llevar armadura pesada.</p>    <h2>Modificadores</h2>   <ul style=\"list-style-type: none; padding-left: 0;\">     <li>+2 Constitución</li>     <li>Competencia: Hacha de mano, Hacha de batalla, Martillo de guerra y Martillo ligero</li>   </ul>', ''),
(4, 'Gnomo', 'Los gnomos son bienvenidos en todas partes como técnicos, alquimistas e inventores, pero muchos de ellos prefieren quedarse entre los suyos aunque sus habilidades estén muy demandadas. Viven en cómodas madrigueras excavadas bajo colinas onduladas y frondosas. Aunque en estos lugares abundan los animales, ir de caza es una pésima idea.', '<h1>Rasgos raciales Gnomo</h1> <p>Tu personaje Gnomo tiene unos cuantos rasgos en común con el resto de miembros de su raza:</p>  <h2>Velocidad</h2> <p>25 pies</p>  <h2>Visión en la oscuridad</h2> <p>Al estar acostumbrado a la vida subterránea, tienes una visión superior en la oscuridad y en la penumbra. Puedes ver en la penumbra a una distancia de 60 pies como si fuera luz brillante, y en la oscuridad como si fuera penumbra. En la oscuridad no puedes distinguir colores, solo tonos de gris.</p>  <h2>Astucia de gnomo</h2> <p>Tienes ventaja en todas las tiradas de salvación de Inteligencia, Sabiduría y Carisma contra magia.</p>  <h2>Idiomas</h2> <p>Puedes hablar, leer y escribir <strong>común</strong> y <strong>gnomo</strong>. El idioma gnomo, que utiliza la grafía enana, es famoso por sus tratados técnicos y sus catálogos de conocimiento sobre el mundo natural.</p>  <h2>Tamaño</h2> <p>Los gnomos miden entre 3 y 4 pies de altura y pesan unas 40 libras de media. Eres de tamaño <strong>Pequeño</strong>.</p>  <h2>Modificadores</h2> <ul style=\"list-style-type: none; padding-left: 0;\">   <li>+2 Inteligencia</li> </ul>', ''),
(5, 'Humano', 'En los registros de la mayoría de los mundos, los humanos son la más joven de las razas comunes. Han llegado comparativamente tarde al mundo y sus vidas son más cortas que las de enanos, elfos y dragones. Y quizá sea precisamente por estas breves existencias por lo que los humanos aspiran a conseguir tanto como sean capaces en los años que se les han concedido..', '<h1>Rasgos raciales Humano</h1> <p>Tu personaje Humano tiene unos cuantos rasgos en común con el resto de miembros de su raza:</p>  <h2>Velocidad</h2> <p>30 pies</p>  <h2>Edad</h2> <p>Alcanzan la madurez poco antes de los veinte años y viven menos de un siglo.</p>  <h2>Alineamiento</h2> <p>Los humanos no tienen tendencia a ningún alineamiento en particular. Entre ellos puede encontrarse tanto lo mejor como lo peor.</p>  <h2>Tamaño</h2> <p>La altura y complexión de los humanos varían enormemente de un individuo a otro, midiendo entre un poco menos de 5 pies y algo más de 6 pies de altura. Independientemente de cual sea tu altura concreta, tu tamaño es <strong>Mediano</strong>.</p>  <h2>Idiomas</h2> <p>Puedes hablar, leer y escribir <strong>común</strong> y un idioma adicional de tu elección. Los humanos normalmente aprenden los idiomas de aquellos con los que se relacionan, aunque sean dialectos poco conocidos. Les gusta adornar su habla con palabras tomadas de otras lenguas: maldiciones orcas, expresiones musicales elfas, términos militares enanos, y así.</p>', ''),
(6, 'Mediano', 'Tu personaje mediano tiene unos cuantos rasgos en común con el resto de medianos. La mayoría de los medianos son neutrales buenos. Como norma general, tienen buen corazón y son amables, odian ver a otros sufrir y no toleran la opresión. También son pacíficos y tradicionales, tienen una fuerte tendencia a apoyar a su comunidad y nunca renuncian a la comodidad de sus costumbres.', '<h1>Rasgos raciales Mediano</h1> <p>Tu personaje Mediano tiene unos cuantos rasgos en común con el resto de miembros de su raza:</p>  <h2>Velocidad</h2> <p>25 pies</p>  <h2>Idiomas</h2> <p>Puedes hablar, leer y escribir <strong>común</strong> y <strong>mediano</strong>. El idioma mediano no es secreto, pero los medianos son reacios a compartirlo con los demás. Escriben muy poco, así que no tienen un corpus literario rico. Por el contrario, su tradición oral es muy amplia. Casi todos los medianos hablan común para conversar con la gente de la tierra en la que viven o por la que viajan.</p>  <h2>Agilidad de los medianos</h2> <p>Puedes moverte por el espacio de cualquier criatura que tenga un tamaño mayor al tuyo.</p>  <h2>Valiente</h2> <p>Tienes ventaja en las tiradas de salvación para no asustarte.</p>  <h2>Afortunado</h2> <p>Cuando saques un 1 en 1d20 en una tirada de ataque, prueba de habilidad o tirada de salvación, puedes volver a tirar el dado, pero debes quedarte con el nuevo resultado.</p>  <h2>Modificadores</h2> <ul style=\"list-style-type: none; padding-left: 0;\">   <li>+2 Destreza</li> </ul>', ''),
(7, 'Semielfo', 'Tu personaje semielfo tiene algunas cracterísticas en común con los elfos y otras que son únicas para los semielfos. Los semielfos comparten la inclinación caótica de su herencia élfica. Valoran tanto la libertad personal como la expresión de la creatividad y no demuestran ni amor por los líderes ni deseo de tener seguidores. Les irritan las reglas, se ofenden ante las exigencias de los demás y a veces son poco fiables o, al menos, impredecibles.', '<h1>Rasgos raciales Semielfo</h1> <p>Tu personaje Semielfo tiene unos cuantos rasgos en común con el resto de miembros de su raza:</p>  <h2>Velocidad</h2> <p>30 pies</p>  <h2>Visión en la oscuridad</h2> <p>Gracias a tu sangre élfica, tienes una visión superior en la oscuridad y en la penumbra. Puedes ver en la penumbra a una distancia de 60 pies como si fuera luz brillante, y en la oscuridad como si fuera penumbra. En la oscuridad no puedes distinguir colores, solo tonos de gris.</p>  <h2>Ancestro feérico</h2> <p>Tienes ventaja en las tiradas de salvación para no quedar hechizado y no puedes quedarte dormido por ningún efecto mágico.</p>  <h2>Idioma</h2> <p>Puedes hablar, leer y escribir <strong>común</strong>, <strong>élfico</strong> y un idioma adicional de tu elección.</p>  <h2>Modificadores</h2> <ul style=\"list-style-type: none; padding-left: 0;\">   <li>+2 Carisma</li>   <li>+1 a dos características a escoger entre Fuerza, Destreza, Constitución, Inteligencia y Sabiduría</li>   <li>Competencia: dos habilidades a escoger</li> </ul>', ''),
(8, 'Semiorco', 'Tu personaje semiorco tiene ciertos rasgos que derivan de su ancestro orco. Los semiorcos heredan la tendencia hacia el caos de sus progenitores orcos y no están muy inclinados hacia el bien. Los semiorcos que se crían entre orcos y que permanecen entre ellos suelen ser malignos.', '<h1>Rasgos raciales Semiorco</h1> <p>Tu personaje Semiorco tiene unos cuantos rasgos en común con el resto de miembros de su raza:</p>  <h2>Velocidad</h2> <p>30 pies</p>  <h2>Visión en la oscuridad</h2> <p>Gracias a tu sangre orca, tienes una visión superior en la oscuridad y en la penumbra. Puedes ver en la penumbra a una distancia de 60 pies como si fuera luz brillante, y en la oscuridad como si fuera penumbra. En la oscuridad no puedes distinguir colores, solo tonos de gris.</p>  <h2>Aguante incansable</h2> <p>Cuando tus puntos de golpe se reducen a 0 pero no mueres inmediatamente, puedes quedarte con 1 punto de golpe. No puedes volver a utilizar esta característica hasta que completes un descanso prolongado.</p>  <h2>Ataques salvajes</h2> <p>Cuando saques un crítico en un ataque con un arma cuerpo a cuerpo, puedes volver a tirar uno de los dados de daño del arma y añadirlo al daño adicional del golpe crítico.</p>  <h2>Idiomas</h2> <p>Puedes hablar, leer y escribir <strong>común</strong> y <strong>orco</strong>. El orco es un idioma áspero, chirriante y con consonantes duras. No tiene grafía propia, se escribe con la grafía enana.</p>  <h2>Edad</h2> <p>Los semiorcos maduran un poco más rápido que los humanos, llegando a la edad adulta en torno a los catorce años. También envejecen visiblemente más deprisa y rara vez viven más de setenta y cinco años.</p>  <h2>Tamaño</h2> <p>Los semiorcos son ligeramente más altos y corpulentos que los humanos, midiendo desde 5 hasta bastante por encima de 6 pies de altura. Eres de tamaño <strong>Mediano</strong>.</p>  <h2>Modificadores</h2> <ul style=\"list-style-type: none; padding-left: 0;\">   <li>Competencia: Intimidar</li> </ul>', ''),
(9, 'Tiefling', 'Puede que los tieflings no tengan una tendencia innata hacia el mal, pero muchos de ellos acaban ahí. Maligna o no, una fuerza externa inclina a muchos tieflings hacia un alineamiento caótico.', '<h1>Rasgos raciales Tiefling</h1> <p>Tu personaje Tiefling tiene unos cuantos rasgos en común con el resto de miembros de su raza:</p>  <h2>Velocidad</h2> <p>30 pies</p>  <h2>Visión en la oscuridad</h2> <p>Gracias a tu herencia infernal, tienes una visión superior en la oscuridad y en la penumbra. Puedes ver en la penumbra a una distancia de 60 pies como si fuera luz brillante, y en la oscuridad como si fuera penumbra. En la oscuridad no puedes distinguir colores, solo tonos de gris.</p>  <h2>Legado infernal</h2> <p>Conoces el truco <strong>Taumaturgia</strong>. Cuando alcanzas el nivel 3, puedes lanzar el conjuro <strong>Reprensión infernal</strong> como un conjuro de nivel 2 una vez con este rasgo y volver a utilizarlo cuando completes un descanso prolongado. Cuando alcanzas el nivel 5, puedes lanzar el conjuro <strong>Oscuridad</strong> una vez con este rasgo y volver a utilizarlo cuando completes un descanso prolongado. La característica con la que lanzas estos conjuros es <strong>Carisma</strong>.</p>  <h2>Resistencia infernal</h2> <p>Tienes resistencia al daño por fuego.</p>  <h2>Idiomas</h2> <p>Puedes hablar, leer y escribir <strong>común</strong> e <strong>infernal</strong>.</p>  <h2>Modificadores</h2> <ul style=\"list-style-type: none; padding-left: 0;\">   <li>+2 Carisma</li>   <li>+1 Inteligencia</li>   <li>Conjuro preparado: Taumaturgia</li>   <li>Conjuro preparado: Reprensión infernal a nivel 3</li>   <li>Conjuro preparado: Oscuridad a nivel 5</li> </ul>', '');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `razas`
--
ALTER TABLE `razas`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `razas`
--
ALTER TABLE `razas`
  MODIFY `id` int(2) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
